### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by Saloed** [alinaib12345/secondTask#1]
1. Настроек вашей среды разработки в репозитории быть не должно. [.idea](https://github.com/alinaib12345/secondTask/tree/master/.idea), [secondTask.iml](https://github.com/alinaib12345/secondTask/blob/master/secondTask.iml).
2. Артефактов сборки в репозитории быть не должно. [out](https://github.com/alinaib12345/secondTask/tree/master/out/), [target](https://github.com/alinaib12345/secondTask/tree/master/target).
3. [Вот этого](https://github.com/alinaib12345/secondTask/blob/master/fileToWrite.txt) в репозитории тоже быть не должно.
4. Большой текст лучше закинуть в файл и оттуда его читать. [link](https://github.com/alinaib12345/secondTask/blob/3d285dec667013708279e43fc8fb6659252af913/test/java/Tests.java#L29)
5. В тестах хотелось бы видеть не только, что оно может запуститься с файлами, но и то, что оно формирует корректный сжатый/разжатый файл. 
6. А что это за проверка с `arguments.get(0).equals("Pack-rle")`? [link](https://github.com/alinaib12345/secondTask/blob/3d285dec667013708279e43fc8fb6659252af913/src/java/PackLauncher.java#L29)
7. Лучше [это](https://github.com/alinaib12345/secondTask/blob/3d285dec667013708279e43fc8fb6659252af913/src/java/PackLauncher.java#L36) тоже сделать опцией.  Там вроде для этих целей есть  [metaVar](https://args4j.kohsuke.org/apidocs/org/kohsuke/args4j/Option.html#metaVar()).
8. Не хорошо в пользователя утилиты исключениями кидаться. [link](https://github.com/alinaib12345/secondTask/blob/3d285dec667013708279e43fc8fb6659252af913/src/java/PackLauncher.java#L31)
9. Кажется, даже с некорректными аргументами утилита запустится и попробует отработать. [link](https://github.com/alinaib12345/secondTask/blob/3d285dec667013708279e43fc8fb6659252af913/src/java/PackLauncher.java#L37)
10. А зачем это нужно? [link](https://github.com/alinaib12345/secondTask/blob/3d285dec667013708279e43fc8fb6659252af913/src/java/PackRle.java#L59)
11. `inputFile` удалять не нужно. У выходного файла по умолчанию имя не должно совпадать с именем входного файла. В задании что-то сказано про расширение. [link](https://github.com/alinaib12345/secondTask/blob/3d285dec667013708279e43fc8fb6659252af913/src/java/PackRle.java#L75)
12. Сжатие, которое работает только в пределах одной строки это не хорошо. [link](https://github.com/alinaib12345/secondTask/blob/3d285dec667013708279e43fc8fb6659252af913/src/java/PackRle.java#L67)
13. Судя по всему, текст вида `В 978 году` лучше не сжимать и не разжимать, а то неизвестно что получится. [link](https://github.com/alinaib12345/secondTask/blob/3d285dec667013708279e43fc8fb6659252af913/src/java/PackRle.java#L45)

**Comment by Saloed** [comment]
1. Ловить все возможные исключения это не хорошо. Лучше как-то по конкретнее указать, что именно вы хотите поймать. [link](https://github.com/alinaib12345/secondTask/blob/ce4fbe8e5076c0c7e4d54eca637200604202384e/src/java/PackLauncher.java#L43)
2. Способ кодирования -- 👍 
3. Есть ощущение, что реализация кодирования может косячить на граничных случаях. Например, когда в файле был ровно 1 байт. 
4. Попробуйте немного переписать [этот](https://github.com/alinaib12345/secondTask/blob/ce4fbe8e5076c0c7e4d54eca637200604202384e/src/java/PackRle.java#L30) кусок. Сейчас выглядит страшновато. Из идей, что можно сделать, кажется, можно немного упростить, если тело цикла разделить на 2 части: 
    - определение нового состояния (продолжение повторения, отличающийся после повторяющихся и т.д.) и изменение счётчиков
    - запись, сброс буфера и счётчиков, если нужно

**Comment by Saloed** [comment]
1. Может [вот это](https://github.com/alinaib12345/secondTask/blob/24cd62add2cf7d43bf9d1f9ccde2143c1f9537c5/src/java/PackRle.java#L71) попробовать сделать [вот здесь](https://github.com/alinaib12345/secondTask/blob/24cd62add2cf7d43bf9d1f9ccde2143c1f9537c5/src/java/PackRle.java#L47)?
2. Может [это](https://github.com/alinaib12345/secondTask/blob/24cd62add2cf7d43bf9d1f9ccde2143c1f9537c5/src/java/PackRle.java#L56) попробовать объединить с [этим](https://github.com/alinaib12345/secondTask/blob/24cd62add2cf7d43bf9d1f9ccde2143c1f9537c5/src/java/PackRle.java#L64)?
3. Может [это](https://github.com/alinaib12345/secondTask/blob/24cd62add2cf7d43bf9d1f9ccde2143c1f9537c5/src/java/PackRle.java#L74) попробовать объединить с [этим](https://github.com/alinaib12345/secondTask/blob/24cd62add2cf7d43bf9d1f9ccde2143c1f9537c5/src/java/PackRle.java#L51)?
4. Было бы хорошо при распаковке, если имя файла не указано, то попробовать убрать у имени входного файла расширение `.rle`, если оно там есть. [link](https://github.com/alinaib12345/secondTask/blob/24cd62add2cf7d43bf9d1f9ccde2143c1f9537c5/src/java/PackLauncher.java#L36)

**Comment by ghhbdtn** [comment]
Исправила, по 1 пункту: notRepetitiveCount должен изменяться не во всех случаях, поэтому его нужно было вынести в отдельное условие !repetitive, если конкретнее, когда после повторяющихся символов встречается другой символ нельзя сразу менять счетчик, т.к. текущий символ может быть началом новой повторяющейся последовательности.

**Comment by Saloed** [comment]
1. `matches` вот с этим условием работает не правильно. Он сейчас просто проверяет, что в строке есть подстрока `.rle` . Например, сейчас имя файла `test.rle.txt` удовлетворяет этому условию. Лучше использовать метод `endsWith`. [link](https://github.com/alinaib12345/secondTask/blob/dda0f138fea94837475b5c08084e53c3da9eb5af/src/java/PackLauncher.java#L39)

**Comment by ghhbdtn** [comment]
Исправила
